---
- name : Install Apache and Upload my Webpage
  hosts : all
  become : true

  vars :
    source_folder : ./my_website2
    dest_folder : /var/www/html

  tasks : 
  - name: Check and Print Linux Version
    debug : var=ansible_os_family 

  - block :  #======Block for Red Hat=========
      - name: Install Apache WebServer for RedHat
        yum : name=httpd state=installed

      - name : Star WebServer and Enable it for RedHat
        service : name=httpd state=started enabled=yes

    when : ansible_os_family="RedHat"

  - block :  #======Block for Debian=========
      - name: Install Apache WebServer for Debian
        apt : name=apache2 state=installed

      - name : Star WebServer and Enable it for Debian
        service : name=apache2 state=started enabled=yes

    when : ansible_os_family="Debian"

  - name : Copy my homepage to servers
    copy : src={{ source_folder }}/{{ item }} dest={{ dest_folder }} mode=0555
    loop :
     - "krot.png"
     - "etc.png"
    notify :
     - Restart Apache for RedHat
     - Restart Apache for Debian

     #############With_FileGlob######################

  - name : Copy my homepage to servers
    copy : src={{ item }}  dest={{ dest_folder }} mode=0555
    with_fileglob : "{{ dest_folder }}/*.*"
    notify :
     - Restart Apache for RedHat
     - Restart Apache for Debian

#Обработчики

  handlers :
  - name : Restart Apache for RedHat
    service : name=httpd state=restarted
    when : ansible_os_family == "RedHat"

  - name : Restart Apache for Debian
    service : name=apache2 state=restarted
    when : ansible_os_family == "Debian"