---
- name : Install Apache and Upload my Webpage
  hosts : "{{ MYHOSTS }}" #all #prod #staging
  become : true

  roles :
   - deploy_apache
  #- { role: deploy_apache, when : ansible_system == 'Linux' }