---
- name : Install Apache and Upload my Webpage
  hosts : all
  become : true

  vars :
    source_file : ./my_website/index.html
    dest_file : /var/www/html

  tasks : 
  - name: Check and Print Linux Version
    debug : var=ansible_os_family 

  - name: Install Apache WebServer for RedHat
    yum : name=httpd state=installed
    when : ansible_os_family="RedHat"

  - name: Install Apache WebServer for Debian
    apt : name=apache2 state=installed
    when : ansible_os_family="Debian"

  - name : Copy my homepage to servers
    copy : src={{ source_file }} dest={{ dest_file }} mode=0555
  #  notify : Restart Apache
    
  - name : Star WebServer and Enable it for RedHat
    service : name=httpd state=started enabled=yes
    when : ansible_os_family="RedHat"

  - name : Star WebServer and Enable it for Debian
    service : name=apache2 state=started enabled=yes
    when : ansible_os_family="Debian"

  handlers :
  - name : Restart Apache for RedHat
    service : name=httpd state=restarted

  - name : Restart Apache for Debian
    service : name=apache2 state=restarted