---
- name : My Super Playbook
  hosts:  all 
  become : true

  vars:
    mytext : "Hello"

  tasks:
    - name : Ping test
      ping :

    #- name : Create folders 
    - include : create_folders.yaml mytext="Hello world!"
    - include : create_files.yaml 
